### PR TITLE
TMatcher.replaceIdentifiers: Replace only the key if it is an 100% match

### PR DESCRIPTION
**Pull request by ErikUniformAgri**
See example in code

### CODE REVIEW

**Comment by hsluoyz** [comment]
@jkour plz review

**Comment by jkour** [comment]
Hi again,

Can you please explain what is the need for this?

Can a test show the difference?

**Comment by ErikUniformAgri** [comment]
I have added an testcase which gives an error in the original code, but does not in the new code.
I only expected a Deny, but it gets accepted somehow. Do you know why? And if thats correct?

**Comment by hsluoyz** [comment]
@jkour

**Comment by jkour** [comment]
Hi,
The RegExpression you added does not replace all the instances of the pair.key. It replaces only the first instance.

**Comment by jkour** [comment]
Actually, the pattern grabs the xxxx= but not the =xxx. You write it your comments

**Comment by ErikUniformAgri** [comment]
All identifiers are replaced now.
As far as I can see the pattern grabs the right part in the string.

**Comment by jkour** [comment]
Great. This looks good. Thx

**Pull request merged**
