### PR TITLE
Make logging optional

### PR DESCRIPTION
**Pull request by ErikUniformAgri**
Use an .inc file to enable/disable logging.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@jkour plz review

**Comment by jkour** [comment]
Hi,
the Logger has an Enabled property already.

I think that what you are trying to do is to disable logging in the console during debug time. Adding a new compiler define may not be the right approach here. It has to be enabled/disabled manually and in the production build one may forget it.

I think it is better if we add another property in the logger (e.g., EnableConsole?) which controls this. 

Then, we add something like {$IF DEBUG}....

**Comment by ErikUniformAgri** [comment]
I removed the .inc file and used the enabled property instead. I don't see any point in adding another property like EnabledConsole, since the Enabled property was not even used

**Comment by jkour** [comment]
I think the best is to implement an EnableConsole property. I will do this in the next commit 

The enabled property is not used because the default logger does not log anything. The property can be used in inherited classes

**Pull request closed without merging**
