### PR TITLE
Use IPMatch to check if link exists

### PR DESCRIPTION
**Pull request by ErikUniformAgri**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@jkour plz review

**Comment by jkour** [comment]
Hi,

I will check in the next couple of days. 

Thanks

**Comment by jkour** [comment]
Hey,

Shall we add the aInvalidIPAsError argument in the original function with a default value to avoid adding a new function?

**Comment by hsluoyz** [comment]
@ErikUniformAgri

**Comment by ErikUniformAgri** [comment]
That does not compile, considering it is used as in a dictionary of TFunctions:

[dcc32 Error] Casbin.Functions.pas(139): E2009 Incompatible types: 'Parameter lists differ'

**Comment by jkour** [comment]
Yes, it doesn't complie.

Thanks

**Pull request merged**
